apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../configs/promotables/tst
- ../../base

namespace: kla2-tst

patchesStrategicMerge:
- version-patch.yaml
- release-patch.yaml