apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../configs/promotables/tst
- git::http://github.com/rkdutta/app-repo.git//deploy/base

namespace: tenant-kla-tst

patchesStrategicMerge:
- version-patch.yaml
- values-patch.yaml